developments:
  storehouse:
    title: Storehouse
    icon: CHEST
    prerequisites:
    initialCost:
    upkeepCost:
    isCollector: false
    isWall: false
    isStorehouse: true
    resource:
  gun:
    title: Gun
    icon: BOW
    prerequisites:
      - storehouse
    initialCost:
      IRON_INGOT: 10
      SMOOTH_STONE: 10
      WHEAT: 10
      OAK_LOG: 10
    upkeepCost:
    isCollector: true
    resource: GUN
  butter:
    title: Butter
    icon: YELLOW_CONCRETE
    prerequisites:
      - storehouse
    initialCost:
      IRON_INGOT: 10
      SMOOTH_STONE: 10
      WHEAT: 10
      OAK_LOG: 10
    upkeepCost:
    isCollector: true
    resource: BUTTER
    