developments:
  storehouse:
    name: Storehouse
    icon: CHEST
    prerequisites:
    initialCost:
    upkeepCost:
      WHEAT: 1
    isCollector: false
    isWall: false
    isStorehouse: true
    resource:
  granary:
    name: Granary
    icon: BREAD
    prerequisites:
      - storehouse
    initialCost:
      OAK_LOG: 10
      SMOOTH_STONE: 5
    upkeepCost:
      WHEAT: 1
    isCollector: true
    isStorehouse: false
    resource: WHEAT
  loggingCamp:
    name: Logging Camp
    icon: IRON_AXE
    prerequisites:
      - storehouse
    initialCost:
      IRON_INGOT: 5
      SMOOTH_STONE: 5
    upkeepCost:
      WHEAT: 1
    isCollector: true
    isWall: false
    resource: OAK_LOG
  quarry:
    name: Quarry
    icon: SMOOTH_STONE
    prerequisites:
      - storehouse
    initialCost:
      IRON_INGOT: 5
      SMOOTH_STONE: 5
    upkeepCost:
      WHEAT: 1
    isCollector: true
    isWall: false
    resource: SMOOTH_STONE
  ironMine:
    name: Iron Mine
    icon: IRON_PICKAXE
    prerequisites:
      - storehouse
    initialCost:
      IRON_INGOT: 5
      SMOOTH_STONE: 5
    upkeepCost:
      WHEAT: 1
    isCollector: true
    isWall: false
    resource: IRON_INGOT
    