name: ${project.name}
main: com.gmail.sharpcastle33.Nobility
version: ${project.version}
commands:
   nobility:
      description: (OP ONLY) debug command for setting an enchant on an item
      usage: with an item in main hand /gce <enchant> <level>
      aliases: [ n ]

