name: ${project.name}
main: net.civex4.nobility.Nobility
version: ${project.version}
depend: [NobilityRegions]
api-version: 1.13
commands:
   nobility:
      description: nobility
      usage: you didn't do the command properly
      aliases: [ n ]
   test:
      description: Tests stuff
